name: test-ros-talker-listener-{name}
download: git clone https://github.com/snapcraft-docs/ros-talker-listener
createDir: |
  cd ros-talker-listener
  $EDITOR snapcraft.yaml
metadata: |
  name: ros-talker-listener
  version: '0.1'
  summary: ROS Talker/Listener Example
  description: |
    This example launches a ROS talker and listener.
explain:
  metadata:
    - text: The name must be unique in the Snap Store. Valid snap names consist of lower-case alphanumeric characters and hyphens. They cannot be all numbers. They also cannot start or end with a hyphen.
    - code: |
        name: ros-talker-listener
    - warning: |
        <span class="p-notification__status">Snap names are globally unique.</span> You should change any instance of <code>ros-talker-listener</code> to <code>test-ros-talker-listener-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official ros-talker-listener snap.
    - text: Versions carry no semantic meaning in snaps. Use text that best identifies that release, it won't be used to compare against the preceding or following one.
    - code: |
        version: '0.1'
    - text: The summary can not exceed 79 characters. You can use a pipe ‘|’ in the description key to declare a multi-line description.
    - code: |
        description: |
  security:
    - text: The next section describes the level of confinement applied to your app.
    - code: |
        confinement: devmode
    - text: Snaps are containerised to ensure more predictable application behaviour and greater security.
    - text: It’s best to start a snap with the confinement in warning mode, rather than strictly applied. This is indicated through the <code>devmode</code> keyword.
    - text: Once an app is working well in devmode, you can review confinement violations, add appropriate interfaces, and switch to strict confinement.
  base:
    - text: In general, snaps cannot see the root filesystem on end user systems. This prevents conflict with other applications and increases security. However, applications still need some location to act as the root filesystem. They would also benefit from common libraries (e.g. libc) being in this root filesystem rather than bundled into each application.
    - text: The base keyword specifies a special kind of snap that provides a minimal set of libraries common to most applications. It will be mounted as the root filesystem for your application.
    - code: |
        base: core18
    - text: The <code>core18</code> base is recommended.
  parts:
    - text: |
        Parts define what sources are needed to assemble your app. Parts can be anything: programs, libraries, or other needed assets. The <code>catkin</code> plugin is useful when building ROS application parts.
    - code: |
        parts:
          ros-tutorials:
            plugin: catkin
            source: https://github.com/ros/ros_tutorials.git
            source-branch: melodic-devel
            source-space: roscpp_tutorials/
    - text: |
        The ROS distro used is determined entirely from the base. With <code>base16</code>, <code>Kinetic</code> is used. With <code>base18</code>, <code>Melodic</code> is used. The <code>source-space</code> points to the source space containing the Catkin tutorial packages. The command <code>snapcraft help catkin</code> gives more information on how this plugin works.
  apps:
    - text: Apps are the commands you want to expose to users and any background services your application provides.
    - code: |
        apps:
          ros-talker-listener:
            command: roslaunch roscpp_tutorials talker_listener.launch
    - warning: |
        <span class="p-notification__status">Snap names are globally unique.</span> You should change any instance of <code>ros-talker-listener</code> to <code>test-ros-talker-listener-{name}</code> (where <code>{name}</code> is your name) before continuing to avoid conflicting with the official ros-talker-listener snap.
    - text: The <code>command</code> specifies the path to the binary to be run. This is resolved relative to the root of your snap contents and automatically searches in the usr/sbin, usr/bin, sbin, and bin subdirectories of your snap.
    - text: If your command name matches the snap name, users will be able run the command directly.
