name: ${name}
version: '0.1'
summary: ROS Talker/Listener Example
description: |
  This example launches a ROS talker and listener.

base: core18
confinement: devmode

parts:
  ros-tutorials:
    plugin: catkin
    source: https://github.com/ros/ros_tutorials.git
    source-branch: melodic-devel
    source-space: roscpp_tutorials/
    build-packages: [lsb-release]

apps:
  run:
    command: roslaunch roscpp_tutorials talker_listener.launch
