#! /usr/bin/env bash

set -e

RUN_COMMAND="gunicorn webapp.app:create_app() --bind $1 --worker-class gevent --workers 2 --name `hostname`"

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
    RUN_COMMAND="${RUN_COMMAND} --logger-class canonicalwebteam.flask_base.log_utils.GunicornDevLogger"
fi

${RUN_COMMAND}
