#! /usr/bin/env bash

set -e

if ["${ENVIRONMENT}" = "production"]; then
    RUN_COMMAND="talisker.gunicorn.gevent webapp.app:create_app() --bind $1 --worker-class gevent --workers 2 --name talisker-`hostname`"
else
    RUN_COMMAND="talisker.gunicorn.gevent webapp_beta.app:app --bind $1 --worker-class gevent --workers 2 --name talisker-`hostname`"
fi

if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
fi

${RUN_COMMAND}
