module.exports = {
  "cookie-policy": "./static/js/base/cookie-policy.ts",
  "global-nav": "./static/js/base/global-nav.ts",
  base: "./static/js/base/base.ts",
  about: "./static/js/public/about/index.ts",
  "featured-snaps": "./static/js/public/featured-snaps.ts",
  modal: "./static/js/public/modal.ts",
  homepage: "./static/js/public/homepage.ts",
  blog: "./static/js/public/blog.ts",
  "store-details": "./static/js/public/store-details.ts",
  fsf: "./static/js/public/fsf.ts",
  "distro-install": "./static/js/public/distro-install.ts",
  "publisher-details": "./static/js/public/publisher-details.ts",
  "about-listing": "./static/js/public/about/listing.ts",
  store: "./static/js/store/index.tsx",
  publisher: "./static/js/publisher/publisher.tsx",
  "brand-store": "./static/js/publisher/brand-store.tsx",
};
