name: ros2-talker-listener-{name}
linux:
  auto:
    - action: "Create a directory, move the downloaded snapcraft.yaml file into the new directory and navigate there:"
      command: mkdir ~/${name} && mv ~/Downloads/snapcraft.yaml ~/${name} && cd  ~/${name}
    - action: "Run snapcraft:"
      command: snapcraft
    - warning: |
        Make sure the name matches what has been used previously (i.e <code>${name}</code>)
macos:
  auto:
    - action: "Create a directory, move the downloaded snapcraft.yaml file into the new directory and navigate there:"
      command: mkdir ~/${name} && mv ~/Downloads/snapcraft.yaml ~/${name} && cd  ~/${name}
    - action: "Run snapcraft:"
      command: snapcraft
windows:
  auto:
    - action: Run Windows Subsystem for Linux from the Windows Start menu
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run snapcraft:"
      command: snapcraft
