name: ${name}
version: '0.1'
summary: ROS2 Talker/Listener Example
description: |
  This example launches a ROS2 talker and listener.
confinement: devmode
base: core18

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: dashing
    colcon-rosdistro: dashing
    colcon-source-space: demo_nodes_cpp
    stage-packages: [ros-dashing-ros2launch]

apps:
  ${name}:
    command: opt/ros/dashing/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
