export const mockRevisions = [
  {
    architectures: ["arm64"],
    attributes: {},
    base: null,
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T09:31:13Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": null,
      paused: null,
      percentage: null,
    },
    revision: 61,
    "sha3-384": "shastring",
    size: 44556288,
    status: "Published",
    version: "4.0.1",
  },
  {
    architectures: ["arm64"],
    attributes: {},
    base: null,
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": null,
      paused: null,
      percentage: null,
    },
    revision: 58,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
  {
    architectures: ["arm64"],
    attributes: {},
    base: null,
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": 30,
      paused: null,
      percentage: null,
    },
    revision: 54,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
];
