import { Revision } from "../types/releaseTypes";

export const mockRevisions: Revision[] = [
  {
    architectures: ["arm64"],
    attributes: {},
    base: "coreXX",
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T09:31:13Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": null,
      percentage: null,
    },
    revision: 61,
    "sha3-384": "shastring",
    size: 44556288,
    status: "Published",
    version: "4.0.1",
  },
  {
    architectures: ["arm64"],
    attributes: {},
    base: "coreXX",
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": null,
      percentage: null,
    },
    revision: 58,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
  {
    architectures: ["arm64"],
    attributes: {},
    base: "coreXX",
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    progressive: {
      "current-percentage": 30,
      percentage: null,
    },
    revision: 54,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
];

export const mockRevisionsMultipleArchs: Revision[] = [
  {
    architectures: ["amd64"],
    attributes: {},
    base: "coreXX",
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    revision: 62,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
  {
    architectures: ["armhf"],
    attributes: {},
    base: "coreXX",
    build_url: "https://example.com/build",
    channels: ["latest/edge"],
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    revision: 63,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
  },
];

export function createMockRevision(
  partialRevision: Partial<Revision>,
): Revision {
  return {
    architectures: ["amd64"],
    attributes: {},
    base: "",
    build_url: null,
    confinement: "strict",
    created_at: "2025-05-01T06:45:23Z",
    epoch: {
      read: [0],
      write: [0],
    },
    expiration: null,
    grade: "stable",
    revision: 63,
    "sha3-384": "shastring",
    size: 46874624,
    status: "Published",
    version: "4.0.1",
    // add custom passed props
    ...partialRevision,
  } as Revision;
}
