export const mockReleases = [
  {
    architecture: "arm64",
    branch: null,
    channel: "latest/stable",
    "expiration-date": null,
    progressive: {
      "current-percentage": null,
      paused: null,
      percentage: null,
    },
    revision: 61,
    risk: "edge",
    track: "latest",
    when: "2025-05-01T09:31:37Z",
  },
  {
    architecture: "arm64",
    branch: "ubuntu-core-desktop",
    channel: "latest/edge",
    "expiration-date": null,
    progressive: {
      "current-percentage": null,
      paused: null,
      percentage: null,
    },
    revision: 58,
    risk: "stable",
    track: "latest",
    when: "2025-04-30T18:21:01Z",
  },
  {
    architecture: "arm64",
    branch: "ubuntu-core-desktop",
    channel: "latest/edge",
    "expiration-date": null,
    progressive: {
      "current-percentage": null,
      paused: null,
      percentage: 10,
    },
    revision: 54,
    risk: "stable",
    track: "latest",
    when: "2025-04-30T18:21:01Z",
  },
];
