---

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: ~/project

version: 2
jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt
      - run:
          name: Build the site resources
          command: yarn run build
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 3 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Lint webapp with Black
          command: yarn run lint-python
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
  lint-js:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Lint statics with eslint
          command: yarn run lint-js
  test-js:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Run tests with jest
          command: |
            yarn run test-js
            bash <(curl -s https://codecov.io/bash) -cF javascript
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Lint scss with sass-lint
          command: yarn run lint-scss
workflows:
  version: 2
  build:
    jobs:
      - test-site
      - lint-python
      - test-python
      - lint-js
      - test-js
      - lint-scss
