export const mockListingData = {
  banner_urls: ["https://example.com/screenshot"],
  categories: [
    { name: "Test category 1", slug: "test-category-1" },
    { name: "Test category 2", slug: "test-category-2" },
  ],
  contacts: [{ url: "https://example.com/contact" }],
  description: "lorem ipsum dolor sit amet",
  donations: [{ url: "https://example.com/donate" }],
  icon_url: "https://example.com/icon",
  issues: [{ url: "https://example.com/issues" }],
  license: "test-license",
  license_type: "test",
  licenses: [{ key: "test", name: "test" }],
  primary_category: "test-category-1",
  primary_website: "https://example.com",
  public_metrics_blacklist: [
    "weekly_installed_base_by_operating_system_normalized",
  ],
  public_metrics_distros: false,
  public_metrics_enabled: false,
  public_metrics_territories: false,
  screenshot_urls: ["https://example.com/screenshot"],
  secondary_category: "test-category-2",
  snap_id: "test_id",
  source_code: [{ url: "https://example.com/code" }],
  summary: "lorem ispum",
  title: "test-snap",
  tour_steps: [
    {
      content:
        "<p>Here you can manage the display of your snap listing within the store.</p><p>We’ll give you a quick tour to get you up to speed!</p>",
      id: "listing-intro",
      title: "Welcome to your snap listing page!",
    },
  ],
  update_metadata_on_release: false,
  video_urls: "https://example.com/video",
  websites: [{ url: "https://example.com" }],
};
