#!/usr/bin/env python3

"""Generate interface metadata from the snap-docs markdown table.

How to run:
    python3 scripts/create-interface-docs-map.py

Arguments:
    --url URL
        Optional markdown URL to fetch.
        Default:
        https://raw.githubusercontent.com/canonical/snap-docs/refs/heads/main/docs/reference/interfaces/index.md

    --output PATH
        Optional output path for the generated Python file.
        Default: webapp/store/content/snap_interfaces_from_docs.py
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from pprint import pformat
from urllib.request import urlopen

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_URL = (
    "https://raw.githubusercontent.com/canonical/snap-docs/refs/heads/main/"
    "docs/reference/interfaces/index.md"
)
DEFAULT_OUTPUT_PATH = (
    ROOT_DIR / "webapp/store/content/snap_interfaces_from_docs.py"
)


def fetch_markdown(url: str) -> str:
    """Fetch markdown content from URL."""

    with urlopen(url, timeout=30) as response:  # nosec B310
        return response.read().decode("utf-8")


def parse_interface_name(interface_cell: str) -> str:
    """Parse the interface name from the table's Interface column text."""

    text = interface_cell.strip()

    if text.startswith("{ref}`") and text.endswith("`"):
        text = text[len("{ref}`") : -1].strip()

    if "<" in text:
        text = text.split("<", 1)[0].strip()

    text = text.strip("`").strip()

    if text.endswith("-interface"):
        text = text[: -len("-interface")]

    return text


def parse_table(markdown: str) -> dict[str, dict[str, object]]:
    """Parse interface table by filtering `|` rows and splitting on `|`."""

    interface_map: dict[str, dict[str, object]] = {}

    for raw_line in markdown.splitlines():
        line = raw_line.strip()
        if not line.startswith("|"):
            continue

        columns = [column.strip() for column in line.split("|")[1:-1]]
        if len(columns) != 4:
            continue

        interface_col, description, categories_col, auto_connect = columns

        if interface_col.lower() == "interface":
            continue

        if all(re.fullmatch(r"-+", col) for col in columns):
            continue

        interface_name = parse_interface_name(interface_col)
        categories = [
            category.strip() for category in categories_col.split(",")
        ]
        categories = [category for category in categories if category]

        if not interface_name:
            raise ValueError(
                f"Could not parse interface name from row: {raw_line!r}"
            )

        if interface_name in interface_map:
            raise ValueError(
                f"Duplicate interface entry found: {interface_name}"
            )

        interface_map[interface_name] = {
            "description": description.strip(),
            "categories": categories,
            "auto_connect": auto_connect.strip(),
        }

    return dict(sorted(interface_map.items()))


def write_output(
    interface_map: dict[str, dict[str, object]], output_path: Path
) -> None:
    """Write parsed interface data to a Python module."""

    output_path.parent.mkdir(parents=True, exist_ok=True)

    rendered = pformat(interface_map, sort_dicts=True, width=100)
    content = (
        "# Auto-generated by scripts/create-interface-docs-map.py\n"
        "# flake8: noqa\n"
        "# fmt: off\n"
        "# To update SNAP_INTERFACE_DETAILS, run:\n"
        "#   python3 scripts/create-interface-docs-map.py\n"
        "# Do not edit by hand.\n\n"
        f"SNAP_INTERFACE_DETAILS = {rendered}\n"
    )

    output_path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch the snap-docs interface markdown and generate a Python map "
            "with interface description, categories, and auto-connect status."
        )
    )
    parser.add_argument(
        "--url",
        default=DEFAULT_SOURCE_URL,
        help=f"Source markdown URL (default: {DEFAULT_SOURCE_URL})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=(
            "Path to write generated Python file "
            f"(default: {DEFAULT_OUTPUT_PATH})"
        ),
    )
    args = parser.parse_args()

    markdown = fetch_markdown(args.url)
    interface_map = parse_table(markdown)
    output_path = (
        args.output if args.output.is_absolute() else Path.cwd() / args.output
    )

    write_output(interface_map, output_path)
    print(f"Wrote {len(interface_map)} interfaces to {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
