def get_countries():
    return {
        "533": {
            "name": "Aruba",
            "code": "AW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "004": {
            "name": "Afghanistan",
            "code": "AF",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "024": {
            "name": "Angola",
            "code": "AO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "660": {
            "name": "Anguilla",
            "code": "AI",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "248": {
            "name": "Åland Islands",
            "code": "AX",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "008": {
            "name": "Albania",
            "code": "AL",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "020": {
            "name": "Andorra",
            "code": "AD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "784": {
            "name": "United Arab Emirates",
            "code": "AE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "032": {
            "name": "Argentina",
            "code": "AR",
            "percentage_of_users": 0.025,
            "color_rgb": [190, 213, 206],
        },
        "051": {
            "name": "Armenia",
            "code": "AM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "016": {
            "name": "American Samoa",
            "code": "AS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "010": {
            "name": "Antarctica",
            "code": "AQ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "260": {
            "name": "French Southern Territories",
            "code": "TF",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "028": {
            "name": "Antigua and Barbuda",
            "code": "AG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "036": {
            "name": "Australia",
            "code": "AU",
            "percentage_of_users": 0.015,
            "color_rgb": [206, 226, 213],
        },
        "040": {
            "name": "Austria",
            "code": "AT",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "031": {
            "name": "Azerbaijan",
            "code": "AZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "108": {
            "name": "Burundi",
            "code": "BI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "056": {
            "name": "Belgium",
            "code": "BE",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "204": {
            "name": "Benin",
            "code": "BJ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "535": {
            "name": "Bonaire, Sint Eustatius and Saba",
            "code": "BQ",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "854": {
            "name": "Burkina Faso",
            "code": "BF",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "050": {
            "name": "Bangladesh",
            "code": "BD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "100": {
            "name": "Bulgaria",
            "code": "BG",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "048": {
            "name": "Bahrain",
            "code": "BH",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "044": {
            "name": "Bahamas",
            "code": "BS",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "070": {
            "name": "Bosnia and Herzegovina",
            "code": "BA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "652": {
            "name": "Saint Barthélemy",
            "code": "BL",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "112": {
            "name": "Belarus",
            "code": "BY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "084": {
            "name": "Belize",
            "code": "BZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "060": {
            "name": "Bermuda",
            "code": "BM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "068": {
            "name": "Bolivia",
            "code": "BO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "076": {
            "name": "Brazil",
            "code": "BR",
            "percentage_of_users": 0.095,
            "color_rgb": [84, 126, 161],
        },
        "052": {
            "name": "Barbados",
            "code": "BB",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "096": {
            "name": "Brunei Darussalam",
            "code": "BN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "064": {
            "name": "Bhutan",
            "code": "BT",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "074": {
            "name": "Bouvet Island",
            "code": "BV",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "072": {
            "name": "Botswana",
            "code": "BW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "140": {
            "name": "Central African Republic",
            "code": "CF",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "124": {
            "name": "Canada",
            "code": "CA",
            "percentage_of_users": 0.03,
            "color_rgb": [183, 207, 203],
        },
        "166": {
            "name": "Cocos (Keeling) Islands",
            "code": "CC",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "756": {
            "name": "Switzerland",
            "code": "CH",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "152": {
            "name": "Chile",
            "code": "CL",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "156": {
            "name": "China",
            "code": "CN",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "384": {
            "name": "Côte d'Ivoire",
            "code": "CI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "120": {
            "name": "Cameroon",
            "code": "CM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "180": {
            "name": "Congo, The Democratic Republic of the",
            "code": "CD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "178": {
            "name": "Congo",
            "code": "CG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "184": {
            "name": "Cook Islands",
            "code": "CK",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "170": {
            "name": "Colombia",
            "code": "CO",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "174": {
            "name": "Comoros",
            "code": "KM",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "132": {
            "name": "Cabo Verde",
            "code": "CV",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "188": {
            "name": "Costa Rica",
            "code": "CR",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "192": {
            "name": "Cuba",
            "code": "CU",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "531": {
            "name": "Curaçao",
            "code": "CW",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "162": {
            "name": "Christmas Island",
            "code": "CX",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "136": {
            "name": "Cayman Islands",
            "code": "KY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "196": {
            "name": "Cyprus",
            "code": "CY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "203": {
            "name": "Czechia",
            "code": "CZ",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "276": {
            "name": "Germany",
            "code": "DE",
            "percentage_of_users": 0.09,
            "color_rgb": [91, 132, 164],
        },
        "262": {
            "name": "Djibouti",
            "code": "DJ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "212": {
            "name": "Dominica",
            "code": "DM",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "208": {
            "name": "Denmark",
            "code": "DK",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "214": {
            "name": "Dominican Republic",
            "code": "DO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "012": {
            "name": "Algeria",
            "code": "DZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "218": {
            "name": "Ecuador",
            "code": "EC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "818": {
            "name": "Egypt",
            "code": "EG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "232": {
            "name": "Eritrea",
            "code": "ER",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "732": {
            "name": "Western Sahara",
            "code": "EH",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "724": {
            "name": "Spain",
            "code": "ES",
            "percentage_of_users": 0.06,
            "color_rgb": [137, 170, 184],
        },
        "233": {
            "name": "Estonia",
            "code": "EE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "231": {
            "name": "Ethiopia",
            "code": "ET",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "246": {
            "name": "Finland",
            "code": "FI",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "242": {
            "name": "Fiji",
            "code": "FJ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "238": {
            "name": "Falkland Islands (Malvinas)",
            "code": "FK",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "250": {
            "name": "France",
            "code": "FR",
            "percentage_of_users": 0.055,
            "color_rgb": [145, 176, 187],
        },
        "234": {
            "name": "Faroe Islands",
            "code": "FO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "583": {
            "name": "Micronesia, Federated States of",
            "code": "FM",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "266": {
            "name": "Gabon",
            "code": "GA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "826": {
            "name": "United Kingdom",
            "code": "GB",
            "percentage_of_users": 0.045,
            "color_rgb": [160, 188, 193],
        },
        "268": {
            "name": "Georgia",
            "code": "GE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "831": {
            "name": "Guernsey",
            "code": "GG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "288": {
            "name": "Ghana",
            "code": "GH",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "292": {
            "name": "Gibraltar",
            "code": "GI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "324": {
            "name": "Guinea",
            "code": "GN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "312": {
            "name": "Guadeloupe",
            "code": "GP",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "270": {
            "name": "Gambia",
            "code": "GM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "624": {
            "name": "Guinea-Bissau",
            "code": "GW",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "226": {
            "name": "Equatorial Guinea",
            "code": "GQ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "300": {
            "name": "Greece",
            "code": "GR",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "308": {
            "name": "Grenada",
            "code": "GD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "304": {
            "name": "Greenland",
            "code": "GL",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "320": {
            "name": "Guatemala",
            "code": "GT",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "254": {
            "name": "French Guiana",
            "code": "GF",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "316": {
            "name": "Guam",
            "code": "GU",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "328": {
            "name": "Guyana",
            "code": "GY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "344": {
            "name": "Hong Kong",
            "code": "HK",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "334": {
            "name": "Heard Island and McDonald Islands",
            "code": "HM",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "340": {
            "name": "Honduras",
            "code": "HN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "191": {
            "name": "Croatia",
            "code": "HR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "332": {
            "name": "Haiti",
            "code": "HT",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "348": {
            "name": "Hungary",
            "code": "HU",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "360": {
            "name": "Indonesia",
            "code": "ID",
            "percentage_of_users": 0.015,
            "color_rgb": [206, 226, 213],
        },
        "833": {
            "name": "Isle of Man",
            "code": "IM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "356": {
            "name": "India",
            "code": "IN",
            "percentage_of_users": 0.02,
            "color_rgb": [198, 220, 210],
        },
        "086": {
            "name": "British Indian Ocean Territory",
            "code": "IO",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "372": {
            "name": "Ireland",
            "code": "IE",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "364": {
            "name": "Iran, Islamic Republic of",
            "code": "IR",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "368": {
            "name": "Iraq",
            "code": "IQ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "352": {
            "name": "Iceland",
            "code": "IS",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "376": {
            "name": "Israel",
            "code": "IL",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "380": {
            "name": "Italy",
            "code": "IT",
            "percentage_of_users": 0.04,
            "color_rgb": [168, 195, 197],
        },
        "388": {
            "name": "Jamaica",
            "code": "JM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "832": {
            "name": "Jersey",
            "code": "JE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "400": {
            "name": "Jordan",
            "code": "JO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "392": {
            "name": "Japan",
            "code": "JP",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "398": {
            "name": "Kazakhstan",
            "code": "KZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "404": {
            "name": "Kenya",
            "code": "KE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "417": {
            "name": "Kyrgyzstan",
            "code": "KG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "116": {
            "name": "Cambodia",
            "code": "KH",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "296": {
            "name": "Kiribati",
            "code": "KI",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "659": {
            "name": "Saint Kitts and Nevis",
            "code": "KN",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "410": {
            "name": "Korea, Republic of",
            "code": "KR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "414": {
            "name": "Kuwait",
            "code": "KW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "418": {
            "name": "Lao People's Democratic Republic",
            "code": "LA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "422": {
            "name": "Lebanon",
            "code": "LB",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "430": {
            "name": "Liberia",
            "code": "LR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "434": {
            "name": "Libya",
            "code": "LY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "662": {
            "name": "Saint Lucia",
            "code": "LC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "438": {
            "name": "Liechtenstein",
            "code": "LI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "144": {
            "name": "Sri Lanka",
            "code": "LK",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "426": {
            "name": "Lesotho",
            "code": "LS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "440": {
            "name": "Lithuania",
            "code": "LT",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "442": {
            "name": "Luxembourg",
            "code": "LU",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "428": {
            "name": "Latvia",
            "code": "LV",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "446": {
            "name": "Macao",
            "code": "MO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "663": {
            "name": "Saint Martin (French part)",
            "code": "MF",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "504": {
            "name": "Morocco",
            "code": "MA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "492": {
            "name": "Monaco",
            "code": "MC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "498": {
            "name": "Moldova",
            "code": "MD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "450": {
            "name": "Madagascar",
            "code": "MG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "462": {
            "name": "Maldives",
            "code": "MV",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "484": {
            "name": "Mexico",
            "code": "MX",
            "percentage_of_users": 0.03,
            "color_rgb": [183, 207, 203],
        },
        "584": {
            "name": "Marshall Islands",
            "code": "MH",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "807": {
            "name": "Macedonia, Republic of",
            "code": "MK",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "466": {
            "name": "Mali",
            "code": "ML",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "470": {
            "name": "Malta",
            "code": "MT",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "104": {
            "name": "Myanmar",
            "code": "MM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "499": {
            "name": "Montenegro",
            "code": "ME",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "496": {
            "name": "Mongolia",
            "code": "MN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "580": {
            "name": "Northern Mariana Islands",
            "code": "MP",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "508": {
            "name": "Mozambique",
            "code": "MZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "478": {
            "name": "Mauritania",
            "code": "MR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "500": {
            "name": "Montserrat",
            "code": "MS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "474": {
            "name": "Martinique",
            "code": "MQ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "480": {
            "name": "Mauritius",
            "code": "MU",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "454": {
            "name": "Malawi",
            "code": "MW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "458": {
            "name": "Malaysia",
            "code": "MY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "175": {
            "name": "Mayotte",
            "code": "YT",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "516": {
            "name": "Namibia",
            "code": "NA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "540": {
            "name": "New Caledonia",
            "code": "NC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "562": {
            "name": "Niger",
            "code": "NE",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "574": {
            "name": "Norfolk Island",
            "code": "NF",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "566": {
            "name": "Nigeria",
            "code": "NG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "558": {
            "name": "Nicaragua",
            "code": "NI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "570": {
            "name": "Niue",
            "code": "NU",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "528": {
            "name": "Netherlands",
            "code": "NL",
            "percentage_of_users": 0.025,
            "color_rgb": [190, 213, 206],
        },
        "578": {
            "name": "Norway",
            "code": "NO",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "524": {
            "name": "Nepal",
            "code": "NP",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "520": {
            "name": "Nauru",
            "code": "NR",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "554": {
            "name": "New Zealand",
            "code": "NZ",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "512": {
            "name": "Oman",
            "code": "OM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "586": {
            "name": "Pakistan",
            "code": "PK",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "591": {
            "name": "Panama",
            "code": "PA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "612": {
            "name": "Pitcairn",
            "code": "PN",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "604": {
            "name": "Peru",
            "code": "PE",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "608": {
            "name": "Philippines",
            "code": "PH",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "585": {
            "name": "Palau",
            "code": "PW",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "598": {
            "name": "Papua New Guinea",
            "code": "PG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "616": {
            "name": "Poland",
            "code": "PL",
            "percentage_of_users": 0.035,
            "color_rgb": [175, 201, 200],
        },
        "630": {
            "name": "Puerto Rico",
            "code": "PR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "408": {
            "name": "Korea, Democratic People's Republic of",
            "code": "KP",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "620": {
            "name": "Portugal",
            "code": "PT",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "600": {
            "name": "Paraguay",
            "code": "PY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "275": {
            "name": "Palestine, State of",
            "code": "PS",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "258": {
            "name": "French Polynesia",
            "code": "PF",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "634": {
            "name": "Qatar",
            "code": "QA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "638": {
            "name": "Réunion",
            "code": "RE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "642": {
            "name": "Romania",
            "code": "RO",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "643": {
            "name": "Russian Federation",
            "code": "RU",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "646": {
            "name": "Rwanda",
            "code": "RW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "682": {
            "name": "Saudi Arabia",
            "code": "SA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "729": {
            "name": "Sudan",
            "code": "SD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "686": {
            "name": "Senegal",
            "code": "SN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "702": {
            "name": "Singapore",
            "code": "SG",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "239": {
            "name": "South Georgia and the South Sandwich Islands",
            "code": "GS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "654": {
            "name": "Saint Helena, Ascension and Tristan da Cunha",
            "code": "SH",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "744": {
            "name": "Svalbard and Jan Mayen",
            "code": "SJ",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "090": {
            "name": "Solomon Islands",
            "code": "SB",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "694": {
            "name": "Sierra Leone",
            "code": "SL",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "222": {
            "name": "El Salvador",
            "code": "SV",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "674": {
            "name": "San Marino",
            "code": "SM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "706": {
            "name": "Somalia",
            "code": "SO",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "666": {
            "name": "Saint Pierre and Miquelon",
            "code": "PM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "688": {
            "name": "Serbia",
            "code": "RS",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "728": {
            "name": "South Sudan",
            "code": "SS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "678": {
            "name": "Sao Tome and Principe",
            "code": "ST",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "740": {
            "name": "Suriname",
            "code": "SR",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "703": {
            "name": "Slovakia",
            "code": "SK",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "705": {
            "name": "Slovenia",
            "code": "SI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "752": {
            "name": "Sweden",
            "code": "SE",
            "percentage_of_users": 0.02,
            "color_rgb": [198, 220, 210],
        },
        "748": {
            "name": "Swaziland",
            "code": "SZ",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "534": {
            "name": "Sint Maarten (Dutch part)",
            "code": "SX",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "690": {
            "name": "Seychelles",
            "code": "SC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "760": {
            "name": "Syrian Arab Republic",
            "code": "SY",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "796": {
            "name": "Turks and Caicos Islands",
            "code": "TC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "148": {
            "name": "Chad",
            "code": "TD",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "768": {
            "name": "Togo",
            "code": "TG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "764": {
            "name": "Thailand",
            "code": "TH",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "762": {
            "name": "Tajikistan",
            "code": "TJ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "772": {
            "name": "Tokelau",
            "code": "TK",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "795": {
            "name": "Turkmenistan",
            "code": "TM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "626": {
            "name": "Timor-Leste",
            "code": "TL",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "776": {
            "name": "Tonga",
            "code": "TO",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "780": {
            "name": "Trinidad and Tobago",
            "code": "TT",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "788": {
            "name": "Tunisia",
            "code": "TN",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "792": {
            "name": "Turkey",
            "code": "TR",
            "percentage_of_users": 0.01,
            "color_rgb": [213, 232, 216],
        },
        "798": {
            "name": "Tuvalu",
            "code": "TV",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "158": {
            "name": "Taiwan",
            "code": "TW",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "834": {
            "name": "Tanzania",
            "code": "TZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "800": {
            "name": "Uganda",
            "code": "UG",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "804": {
            "name": "Ukraine",
            "code": "UA",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "581": {
            "name": "United States Minor Outlying Islands",
            "code": "UM",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "858": {
            "name": "Uruguay",
            "code": "UY",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "840": {
            "name": "United States",
            "code": "US",
            "percentage_of_users": 0.145,
            "color_rgb": [8, 64, 129],
        },
        "860": {
            "name": "Uzbekistan",
            "code": "UZ",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "336": {
            "name": "Holy See (Vatican City State)",
            "code": "VA",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "670": {
            "name": "Saint Vincent and the Grenadines",
            "code": "VC",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "862": {
            "name": "Venezuela",
            "code": "VE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "092": {
            "name": "Virgin Islands, British",
            "code": "VG",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "850": {
            "name": "Virgin Islands, U.S.",
            "code": "VI",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "704": {
            "name": "Vietnam",
            "code": "VN",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "548": {
            "name": "Vanuatu",
            "code": "VU",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "876": {
            "name": "Wallis and Futuna",
            "code": "WF",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "882": {
            "name": "Samoa",
            "code": "WS",
            "percentage_of_users": 0,
            "color_rgb": [247, 247, 247],
        },
        "887": {
            "name": "Yemen",
            "code": "YE",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "710": {
            "name": "South Africa",
            "code": "ZA",
            "percentage_of_users": 0.005,
            "color_rgb": [221, 238, 219],
        },
        "894": {
            "name": "Zambia",
            "code": "ZM",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
        "716": {
            "name": "Zimbabwe",
            "code": "ZW",
            "percentage_of_users": 0,
            "color_rgb": [229, 245, 223],
        },
    }


def get_normalised_oses():
    return [
        {"name": "ubuntu 18.04", "value": 1.0},
        {"name": "ubuntu 16.04", "value": 0.9},
        {"name": "ubuntu 18.10", "value": 0.875},
        {"name": "ubuntu 17.10", "value": 0.725},
        {"name": "fedora 29", "value": 0.675},
        {"name": "linuxmint 18.3", "value": 0.65},
        {"name": "linuxmint 19", "value": 0.65},
        {"name": "elementary 5.0", "value": 0.65},
        {"name": "linuxmint 19.1", "value": 0.625},
        {"name": "debian 9", "value": 0.625},
        {"name": "neon 18.04", "value": 0.625},
        {"name": "zorin 12", "value": 0.625},
        {"name": "elementary 0.4.1", "value": 0.6},
        {"name": "fedora 28", "value": 0.6},
        {"name": "ubuntu 14.04", "value": 0.575},
        {"name": "manjaro", "value": 0.575},
        {"name": "linuxmint 18.2", "value": 0.55},
        {"name": "ubuntu 19.04", "value": 0.55},
        {"name": "ubuntu 17.04", "value": 0.55},
    ]
