import os

from urllib.parse import urlparse

import flask
from canonicalwebteam.store_api import dashboard as store_api_dashboard
from canonicalwebteam.store_api import publishergw as store_api_publishergw
from pymacaroons import Macaroon
from webapp.api import sso

LOGIN_URL = os.getenv("LOGIN_URL", "https://login.ubuntu.com")

# The bound root+discharge macaroon pair is only needed by the handful of
# legacy SCA (dashboard.snapcraft.io) endpoints that don't accept the
# smaller exchanged token (e.g. unregistering a snap name). Keeping it in
# cookies scoped to those routes, rather than in the session, means the
# cookie sent on every other request stays small.
SCA_AUTH_COOKIE_PATH = "/packages"
SCA_ROOT_COOKIE = "sca_macaroon_root"
SCA_DISCHARGE_COOKIE = "sca_macaroon_discharge"

PERMISSIONS = [
    "edit_account",
    "package_access",
    "package_manage",
    "package_metrics",
    "package_register",
    "package_release",
    "package_update",
    "package_upload_request",
    "store_admin",
]

# keys for session data that should be cleared on auth refresh
SESSION_AUTH_KEYS = [
    "macaroons",
    "macaroon_exchanged",
    "macaroon_root",
    "macaroon_discharge",
    "publisher",
    "developer_token",
    "exchanged_developer_token",
    "csrf_token",
]

# keys for session data that should NOT be cleared on auth refresh
SESSION_INTEGRATION_KEYS = [
    "github_auth_secret",
]

SESSION_DATA_KEYS = SESSION_AUTH_KEYS + SESSION_INTEGRATION_KEYS


def get_authorization_header(macaroon):
    """
    Return the authorization header value for an exchanged macaroon.
    """
    return f"Macaroon {macaroon}"


def get_session_authorization_headers(session):
    """
    Return the SCA (dashboard.snapcraft.io) authorization header for the
    current session. SCA's legacy endpoints (e.g. snap unregister) only
    accept the bound root+discharge macaroon pair, so that's checked first,
    reading it from cookies (see set_sca_auth_cookies) and falling back to
    the session for compatibility with the login handshake and old tests.
    The single exchanged macaroon is NOT valid for these calls, so it's
    only used as a last resort.
    """
    root = flask.request.cookies.get(SCA_ROOT_COOKIE) or session.get(
        "macaroon_root"
    )
    discharge = flask.request.cookies.get(SCA_DISCHARGE_COOKIE) or session.get(
        "macaroon_discharge"
    )

    if root and discharge:
        bound = Macaroon.deserialize(root).prepare_for_request(
            Macaroon.deserialize(discharge)
        )

        return {
            "Authorization": (
                f"macaroon root={root}, discharge={bound.serialize()}"
            )
        }

    if "macaroon_exchanged" in session:
        return {
            "Authorization": get_authorization_header(
                session["macaroon_exchanged"]
            )
        }

    if "macaroons" in session:
        return {"Macaroons": session["macaroons"]}

    return {"Macaroons": ""}


def get_publishergw_authorization_header(developer_token):
    return {"Authorization ": f"Macaroon {developer_token}"}


def set_sca_auth_cookies(response, root, discharge):
    """
    Persist the bound root+discharge macaroon pair in cookies scoped to
    SCA_AUTH_COOKIE_PATH, instead of the session, so most requests don't
    carry them.
    """
    cookie_kwargs = {
        "path": SCA_AUTH_COOKIE_PATH,
        "httponly": True,
        "secure": flask.current_app.config.get("SESSION_COOKIE_SECURE", False),
        "samesite": flask.current_app.config.get("SESSION_COOKIE_SAMESITE"),
    }
    response.set_cookie(SCA_ROOT_COOKIE, root, **cookie_kwargs)
    response.set_cookie(SCA_DISCHARGE_COOKIE, discharge, **cookie_kwargs)


def clear_sca_auth_cookies(response):
    """
    Remove the SCA auth cookies, used on logout and forced re-authentication.
    """
    response.delete_cookie(SCA_ROOT_COOKIE, path=SCA_AUTH_COOKIE_PATH)
    response.delete_cookie(SCA_DISCHARGE_COOKIE, path=SCA_AUTH_COOKIE_PATH)


def is_authenticated(session):
    """
    Checks if the user is authenticated from the session
    Returns True if the user is authenticated
    """
    return (
        ("publisher" in session and "macaroon_exchanged" in session)
        or (
            "publisher" in session
            and "macaroon_discharge" in session
            and "macaroon_root" in session
        )
        or ("publisher" in session and "macaroons" in session)
    )


def empty_session(session):
    """
    Empty the session, used to logout.
    """
    for key in SESSION_DATA_KEYS:
        session.pop(key, None)


def reset_auth_session(session):
    """
    Clear Snapcraft auth keys while preserving integration tokens
    (e.g. github_auth_secret). Used when re-authentication is needed
    but third-party tokens are still valid.
    """
    for key in SESSION_AUTH_KEYS:
        session.pop(key, None)


def get_caveat_id(root):
    """
    Returns the caveat_id generated by the SSO
    """
    location = urlparse(LOGIN_URL).hostname
    (caveat,) = [
        c
        for c in Macaroon.deserialize(root).third_party_caveats()
        if c.location == location
    ]

    return caveat.caveat_id


def request_macaroon():
    """
    Request a macaroon from dashboard.
    Returns the macaroon.
    """
    response = sso.post_macaroon({"permissions": PERMISSIONS})

    return response["macaroon"]


def get_refreshed_discharge(discharge):
    """
    Get a refresh macaroon if the macaroon is not valid anymore.
    Returns the new discharge macaroon.
    """
    response = sso.get_refreshed_discharge({"discharge_macaroon": discharge})

    return response["discharge_macaroon"]


def is_macaroon_expired(headers):
    """
    Returns True if the macaroon needs to be refreshed from
    the header response.
    """
    return headers.get("WWW-Authenticate") == ("Macaroon needs_refresh=1")


def _store_api_authorization_header(_self, session):
    return get_session_authorization_headers(session)


store_api_dashboard.Dashboard._get_authorization_header = (
    _store_api_authorization_header
)
store_api_publishergw.dashboard_authorization_header = (
    get_session_authorization_headers
)
