name: LP Cehckout Test
on: pull_request

env:
  SECRET_KEY: insecure_test_key
  LP_API_USERNAME: test_lp_user

jobs:
  lp-test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Checkout
        run: |
          cat ~/.ssh/config
